package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

var perfArtifactRoot = "artifacts/perf"

func ensureSafePerfCandidatePath(arg, repoRoot string) (string, error) {
	display := pyPathStr(arg)
	if filepath.IsAbs(arg) {
		return "", perr("candidate path must be a relative path under artifacts/perf/: %s", display)
	}
	normalized := filepath.Clean(display)
	if normalized == "." || hasDotDot(normalized) {
		return "", perr("candidate path must be a relative path under artifacts/perf/: %s", display)
	}
	if !isUnder(perfArtifactRoot, normalized) {
		return "", perr("candidate path must be a relative path under artifacts/perf/: %s", display)
	}
	current := repoRoot
	for part := range strings.SplitSeq(normalized, string(filepath.Separator)) {
		current = filepath.Join(current, part)
		if fi, err := os.Lstat(current); err == nil && fi.Mode()&os.ModeSymlink != 0 {
			sym := current
			if rel, rerr := filepath.Rel(repoRoot, current); rerr == nil {
				sym = rel
			}
			return "", perr("candidate path must not traverse symlink under artifacts/perf/: %s", sym)
		}
	}
	return normalized, nil
}

func resolvePackage(repoRoot, pkg string) (string, string, error) {
	if !strings.HasPrefix(pkg, "./") {
		return repoRoot, pkg, nil
	}
	pkgDir := filepath.Join(repoRoot, pkg[2:])
	if !isUnder(resolveSymlinks(repoRoot), resolveSymlinks(pkgDir)) {
		return "", "", perr("benchmark package path must stay under repo root: %s", pkg)
	}
	if !fileExists(pkgDir) {
		return repoRoot, pkg, nil
	}
	moduleDir := ""
	if fileExists(filepath.Join(repoRoot, "go.mod")) {
		moduleDir = repoRoot
	}
	current := pkgDir
	for {
		if fileExists(filepath.Join(current, "go.mod")) {
			moduleDir = current
			break
		}
		if current == repoRoot {
			break
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
		current = parent
	}
	if moduleDir == "" || moduleDir == repoRoot {
		return repoRoot, pkg, nil
	}
	rel, _ := filepath.Rel(moduleDir, pkgDir)
	if rel == "." {
		return moduleDir, ".", nil
	}
	return moduleDir, "./" + filepath.ToSlash(rel), nil
}

func benchRegex(names []string) string {
	escaped := make([]string, len(names))
	for i, n := range names {
		escaped[i] = regexp.QuoteMeta(n)
	}
	return "^(" + strings.Join(escaped, "|") + ")$"
}

var shlexUnsafeRe = regexp.MustCompile(`[^\w@%+=:,./-]`)

func shlexQuote(s string) string {
	if s == "" {
		return "''"
	}
	if !shlexUnsafeRe.MatchString(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

func joinShlex(parts []string) string {
	quoted := make([]string, len(parts))
	for i, p := range parts {
		quoted[i] = shlexQuote(p)
	}
	return strings.Join(quoted, " ")
}

func exitCode(err error) int {
	if ee, ok := errors.AsType[*exec.ExitError](err); ok {
		return ee.ExitCode()
	}
	return 1
}

func collectResults(policy *omap, selected selection, args *cliArgs, repoRoot, repoName string) (int, error) {
	candidateNorm, e := ensureSafePerfCandidatePath(args.candidate, repoRoot)
	if e != nil {
		return 0, e
	}
	if fi, err := os.Stat(candidateNorm); err == nil {
		if !fi.IsDir() {
			fmt.Fprintf(os.Stderr, "error: candidate path exists and is not a directory: %s\n", candidateNorm)
			return 2, nil
		}
		if err := os.RemoveAll(candidateNorm); err != nil {
			return 0, perr("cannot remove %s: %v", candidateNorm, err)
		}
	}
	outputDir := filepath.Join(candidateNorm, "go-bench")
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return 0, perr("cannot create %s: %v", outputDir, err)
	}
	outputFile := filepath.Join(outputDir, repoName+".txt")
	count := policyMinCount(policy)
	if args.count != nil {
		count = *args.count
	}
	benchtime := args.benchtime
	minCount := policyMinCount(policy)
	smokeRun := count < minCount

	byPackage := map[string][]string{}
	for _, en := range selected {
		pkg, _ := mustGet(en.config, "package").(string)
		byPackage[pkg] = append(byPackage[pkg], en.name)
	}
	sortedPkgs := make([]string, 0, len(byPackage))
	for p := range byPackage {
		sortedPkgs = append(sortedPkgs, p)
	}
	slices.Sort(sortedPkgs)

	sink, err := os.Create(outputFile)
	if err != nil {
		return 0, perr("cannot create %s: %v", outputFile, err)
	}
	fmt.Fprintln(sink, "# generated by scripts/perf/check-bench-regression.sh collect")
	fmt.Fprintf(sink, "# repo: %s\n", repoName)
	fmt.Fprintf(sink, "# count: %d\n", count)
	if benchtime != "" {
		fmt.Fprintf(sink, "# benchtime: %s\n", benchtime)
	}
	if smokeRun {
		fmt.Fprintf(sink, "# smoke run: count<min_count count=%d min_count=%d\n", count, minCount)
	}
	if args.gate != "" {
		fmt.Fprintf(sink, "# gate: %s\n", args.gate)
	}
	if gf := os.Getenv("GOFLAGS"); gf != "" {
		fmt.Fprintf(sink, "# goflags: %s\n", gf)
	}

	for _, pkg := range sortedPkgs {
		cwd, pkgArg, re := resolvePackage(repoRoot, pkg)
		if re != nil {
			_ = sink.Close()
			return 0, re
		}
		sortedNames := append([]string(nil), byPackage[pkg]...)
		slices.Sort(sortedNames)
		regex := benchRegex(sortedNames)
		cmdParts := []string{"go", "test", "-run", "^$", "-bench", regex, "-benchmem", fmt.Sprintf("-count=%d", count)}
		if benchtime != "" {
			cmdParts = append(cmdParts, "-benchtime="+benchtime)
		}
		cmdParts = append(cmdParts, pkgArg)
		display := joinShlex(cmdParts)
		if cwd != repoRoot {
			rel, _ := filepath.Rel(repoRoot, cwd)
			display = fmt.Sprintf("(cd %s && %s)", shlexQuote(rel), display)
		}
		fmt.Fprintf(sink, "# package: %s\n", pkg)
		fmt.Fprintf(sink, "# command: %s\n", display)
		_ = sink.Sync()

		var buf bytes.Buffer
		c := exec.Command(cmdParts[0], cmdParts[1:]...)
		c.Dir = cwd
		c.Stdout = &buf
		c.Stderr = &buf
		runErr := c.Run()
		out := buf.Bytes()
		_, _ = sink.Write(out)
		if len(out) > 0 && out[len(out)-1] != '\n' {
			_, _ = sink.Write([]byte("\n"))
		}
		_ = sink.Sync()
		if runErr != nil {
			_ = sink.Close()
			_, _ = os.Stderr.Write(out)
			fmt.Fprintf(os.Stderr, "error: benchmark collection failed for package %s\n", pkg)
			return exitCode(runErr), nil
		}
	}
	_ = sink.Close()

	results, pe := parseResults(candidateNorm)
	if pe != nil {
		return 0, pe
	}
	missing := checkMissing(results, selected)
	if len(missing) > 0 {
		for _, name := range missing {
			fmt.Fprintf(os.Stderr, "error: missing candidate benchmark: %s\n", name)
		}
		return 2, nil
	}
	suffix := ""
	if benchtime != "" {
		suffix = ", benchtime=" + benchtime
	}
	fmt.Printf("collected benchmark results: %s (benchmarks=%d, packages=%d, count=%d%s)\n",
		outputFile, len(selected), len(byPackage), count, suffix)
	if smokeRun {
		fmt.Printf("smoke run: count<min_count (count=%d, min_count=%d)\n", count, minCount)
	}
	return 0, nil
}
